import { v } from "convex/values";
import type { Doc, Id } from "./_generated/dataModel";
import { internalMutation, internalQuery } from "./_generated/server";
import { slugify } from "./lib/slug";

function toSummary(c: Doc<"canvases">) {
  return {
    canvas_id: c._id,
    workspace_id: c.workspaceId,
    slug: c.slug,
    title: c.title,
    description: c.description,
    kind: c.kind,
    visibility: c.visibility,
    public_slug: c.publicSlug,
    theme: c.theme,
    updated_at: c.updatedAt,
  };
}

export const create = internalMutation({
  args: {
    workspaceId: v.id("workspaces"),
    title: v.string(),
    kind: v.union(v.literal("canvas"), v.literal("html"), v.literal("image"), v.literal("pdf")),
    slug: v.optional(v.string()),
    theme: v.optional(v.string()),
    createdBy: v.id("users"),
  },
  handler: async (ctx, args) => {
    const workspace = await ctx.db.get(args.workspaceId);
    if (!workspace) throw new Error(`Unknown workspace: ${args.workspaceId}`);

    const base = slugify(args.slug ?? args.title);
    let slug = base;
    let suffix = 2;
    while (
      await ctx.db
        .query("canvases")
        .withIndex("by_workspace_slug", (q) =>
          q.eq("workspaceId", args.workspaceId).eq("slug", slug),
        )
        .unique()
    ) {
      slug = `${base}-${suffix}`;
      suffix += 1;
    }

    const now = Date.now();
    const canvasId = await ctx.db.insert("canvases", {
      workspaceId: args.workspaceId,
      slug,
      title: args.title,
      kind: args.kind,
      visibility: "private",
      theme: args.theme,
      createdBy: args.createdBy,
      updatedAt: now,
    });
    return { canvasId, slug };
  },
});

export const list = internalQuery({
  args: { workspaceId: v.id("workspaces") },
  handler: async (ctx, args) => {
    const rows = await ctx.db
      .query("canvases")
      .withIndex("by_workspace_updated", (q) => q.eq("workspaceId", args.workspaceId))
      .order("desc")
      .take(200);
    return rows.map(toSummary);
  },
});

export const get = internalQuery({
  args: { canvasId: v.id("canvases") },
  handler: async (ctx, args) => {
    const canvas = await ctx.db.get(args.canvasId);
    if (!canvas) return null;
    let docStorageId: Id<"_storage"> | undefined;
    let version: number | undefined;
    if (canvas.currentVersionId) {
      const currentVersion = await ctx.db.get(canvas.currentVersionId);
      docStorageId = currentVersion?.docStorageId;
      version = currentVersion?.version;
    }
    return { ...toSummary(canvas), doc_storage_id: docStorageId, version };
  },
});

export const publish = internalMutation({
  args: {
    canvasId: v.id("canvases"),
    visibility: v.union(v.literal("private"), v.literal("public")),
    // A fresh 128-bit-random slug, generated by the caller (httpAction —
    // mutations should not mint their own randomness); ignored if the
    // canvas already has one.
    newPublicSlug: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const canvas = await ctx.db.get(args.canvasId);
    if (!canvas) throw new Error(`Unknown canvas: ${args.canvasId}`);

    if (args.visibility === "private") {
      await ctx.db.patch(args.canvasId, { visibility: "private", publicSlug: undefined });
      return { visibility: "private" as const, publicSlug: undefined };
    }

    const publicSlug = canvas.publicSlug ?? args.newPublicSlug;
    if (!publicSlug) {
      throw new Error("newPublicSlug is required the first time a canvas is published");
    }
    await ctx.db.patch(args.canvasId, { visibility: "public", publicSlug });
    return { visibility: "public" as const, publicSlug };
  },
});

export const putDoc = internalMutation({
  args: {
    canvasId: v.id("canvases"),
    docStorageId: v.id("_storage"),
    note: v.optional(v.string()),
    createdBy: v.id("users"),
    nodes: v.array(
      v.object({
        nodeId: v.string(),
        title: v.string(),
        eyebrow: v.optional(v.string()),
        searchText: v.string(),
      }),
    ),
  },
  handler: async (ctx, args) => {
    const canvas = await ctx.db.get(args.canvasId);
    if (!canvas) throw new Error(`Unknown canvas: ${args.canvasId}`);

    const last = await ctx.db
      .query("canvasVersions")
      .withIndex("by_canvas_version", (q) => q.eq("canvasId", args.canvasId))
      .order("desc")
      .first();
    const version = (last?.version ?? 0) + 1;

    const versionId = await ctx.db.insert("canvasVersions", {
      canvasId: args.canvasId,
      version,
      note: args.note,
      createdBy: args.createdBy,
      docStorageId: args.docStorageId,
    });

    for (const node of args.nodes) {
      await ctx.db.insert("canvasNodes", { canvasId: args.canvasId, versionId, ...node });
    }

    await ctx.db.patch(args.canvasId, { currentVersionId: versionId, updatedAt: Date.now() });
    return { versionId, version };
  },
});

export const upsertFile = internalMutation({
  args: {
    canvasId: v.id("canvases"),
    relPath: v.string(),
    storageId: v.id("_storage"),
    size: v.number(),
    contentHash: v.string(),
  },
  handler: async (ctx, args) => {
    const canvas = await ctx.db.get(args.canvasId);
    if (!canvas) throw new Error(`Unknown canvas: ${args.canvasId}`);

    const existing = await ctx.db
      .query("canvasFiles")
      .withIndex("by_canvas_relPath", (q) =>
        q.eq("canvasId", args.canvasId).eq("relPath", args.relPath),
      )
      .unique();

    if (existing) {
      await ctx.db.patch(existing._id, {
        storageId: args.storageId,
        size: args.size,
        contentHash: args.contentHash,
      });
    } else {
      await ctx.db.insert("canvasFiles", {
        canvasId: args.canvasId,
        relPath: args.relPath,
        storageId: args.storageId,
        size: args.size,
        contentHash: args.contentHash,
      });
    }
    await ctx.db.patch(args.canvasId, { updatedAt: Date.now() });
  },
});

export const listArtifactsForCanvas = internalQuery({
  args: { canvasId: v.id("canvases") },
  handler: async (ctx, args) => {
    const rows = await ctx.db
      .query("artifacts")
      .withIndex("by_canvas_relPath", (q) => q.eq("canvasId", args.canvasId))
      .take(500);
    return rows.map((a) => ({ path: a.relPath, type: a.type, role: a.role }));
  },
});

export const getArtifact = internalQuery({
  args: { canvasId: v.id("canvases"), relPath: v.string() },
  handler: async (ctx, args) => {
    const row = await ctx.db
      .query("artifacts")
      .withIndex("by_canvas_relPath", (q) =>
        q.eq("canvasId", args.canvasId).eq("relPath", args.relPath),
      )
      .unique();
    if (!row) return null;
    return {
      path: row.relPath,
      type: row.type,
      role: row.role,
      mimeType: row.mimeType,
      size: row.size,
      storageId: row.storageId,
    };
  },
});
