/**
 * The server's `instructions` string — MCP's channel for telling a client how
 * the server works as a whole, rather than repeating it in every tool
 * description.
 *
 * v1 registered no instructions at all, and several tool descriptions cited
 * "PLAN.md section 7" — a file the caller cannot read. Everything a caller
 * needs to use this server correctly now lives here, once.
 */

import { listTemplates } from "@visual-canvas/runtime/templates/index.js";

export function buildInstructions(): string {
  // Derived from the live registry, not the reference-only TEMPLATE_IDS
  // constant in runtime/types.ts — that one is documentation and can drift.
  const templateIds = listTemplates().map((t) => t.id);
  return [
    "Visual Canvas authors shareable visual documents — diagrams, dashboards, reports, mockups —",
    "and serves them at stable URLs for humans to view and share.",
    "",
    "ADDRESSING. Every canvas tool takes one `ref`: workspace/canvas, canvas id, public slug,",
    "a returned canvas/share URL, or a canvas:// URI. Slug refs create on first save.",
    "Prefer the slug form: it is stable, human-readable, and makes canvas_save idempotent, so a",
    "retried call updates the same canvas instead of creating a duplicate. File paths are never",
    "part of the ref — they go in their own `path` field.",
    "A user may paste an element locator like canvas://osago/fast-settlement?node=phone-checkout.",
    "Pass it unchanged as canvas_get({ref_id}); do not ask them to name the canvas separately.",
    "",
    "AUTHORING. canvas_save creates the workspace and canvas if needed and atomically updates its",
    "durable draft. The first save creates v1; later micro-edits keep the stable version and advance",
    "draft_revision. Call canvas_checkpoint once at a meaningful milestone; publishing checkpoints",
    "the complete draft first. Pass both expected_version and expected_draft_revision for writes.",
    "  kind=canvas          author with CanvasFile version=3 plus files in the same call",
    "  kind=html|image|pdf  author with `files` + `renders`",
    "CanvasFile v3 contains ordered Pages and a canvas-level prototype. Every Page owns an independent",
    "CanvasDoc v2 world; files, assets, checkpoints, visibility and share URL remain canvas-level.",
    "Use canvas_page_* for page operations, canvas_prototype_* for start/hotspot authoring, and",
    "canvas_get/canvas_doc_patch/canvas_snapshot page_id to address one Page without replacing others.",
    "CanvasDoc v2 has explicit world/rect geometry, native|iframe|image node unions, anchors, and groups.",
    "A group is {id,label?,nodeIds:[...]}; its bounds are derived from its member nodes, and moving it",
    "translates every member node by the same dx/dy. Use groups.add/update/remove in canvas_doc_patch.",
    "Use image nodes for static screenshots/reference boards: source.path points at a file or",
    "library binding under /assets (or /src), with fit, focalPosition and required alt text.",
    "lanes, stages, labels, nodes, groups and edges default to empty arrays, so non-diagram boards need",
    "only the collections they actually use.",
    "Iframe entrypoints must be local .html files under /src/screens/; external URLs, traversal and",
    "allow-same-origin are rejected. Upload runtime/CSS/JS/assets with doc atomically. Use render",
    "target {type:'canvas'} for PNG/PDF/thumbnail or {type:'file',entrypoint,route:'#/path'} for",
    "a routed HTML screen. Do not append a hash route to entrypoint itself.",
    "Phone nodes use viewport {width:284,height:642} and frame {kind:'phone',time:'09:42'}.",
    "The canvas owns the canonical OSAGO bezel, notch and status bar. Phone iframe HTML must contain",
    "only screen content; never duplicate a phone shell or status bar inside the entrypoint.",
    "Screens start inactive: single-click selects, double-click or Enter activates; Escape or Exit",
    "returns pointer/keyboard control to pan/zoom. Public share views remain interactive.",
    "For incremental changes use canvas_file_get to read one bounded file, canvas_edit (one exact",
    "old_string/new_string replacement),",
    "canvas_apply_patch (atomic Codex-style multi-file patch), or canvas_doc_patch (typed semantic",
    "graph operations such as nodes.update/nodes.replace). Updates shallow-merge entity roots, so",
    "pass a complete nested rect; replace clears omitted optional fields. Always read first and",
    "pass expected_version, expected_draft_revision where declared, and file hashes. A stale",
    "canvas_edit/apply_patch safely rebases when",
    "the target files still match those hashes; edits never require regenerating the",
    "whole project.",
    "canvas_file_get returns UTF-8 for full/line reads and exact base64 for byte ranges; always",
    "check its encoding field before interpreting content.",
    "",
    "FILE PATHS. Writable: /src (sources), /assets (images, fonts), /output (results).",
    "Read-only: /cache (render scratch, deleted after 24h). Reference assets from your HTML with",
    'root-relative paths like "/assets/logo.png".',
    "",
    "LARGE FILES. Do NOT inline megabytes of base64 into a tool call — it burns context and may",
    "exceed the request limit. Call canvas_upload_url with up to 50 files, follow each returned",
    "method exactly, then pass every returned storageId as files[].upload_id in one canvas_save.",
    "Small text files can go inline via `text`.",
    "",
    "ASSET LIBRARY. asset_list searches personal or workspace media and returns immutable asset://",
    "refs. It is intentionally separate from canvas-private /assets files: canvas_upload_url does",
    "not populate the Library, while asset_upload_url does. Choose Library for cross-canvas reuse.",
    "asset_get(include_preview=true) puts visual media directly in multimodal model context.",
    "Use batch-capable asset_upload_url + asset_finalize (up to 50 items) for binary uploads;",
    "failed finalize items retain upload_id for resume. Use asset_import for an HTTPS source,",
    "and asset_attach (or files[].asset_ref in canvas_save) to pin a revision under /assets/.",
    "asset_move changes personal/workspace scope without re-uploading bytes; its previous ref stops",
    "resolving for new work while existing canvas bindings stay pinned to immutable versions.",
    "After making a personal copy of a workspace asset, call asset_delete on the stale workspace",
    "asset. This archives it without hard-purging shared content-addressed bytes. Call",
    "asset_restore with that asset_ref to return it to its original library when needed.",
    "Updating a library asset never mutates old or current canvas versions automatically.",
    "asset_list is cursor-paginated; continue with next_cursor until is_done=true.",
    "",
    "URLS. canvas_save and canvas_get return real, fully-qualified URLs:",
    "  canvas_url  — the signed-in viewer, for teammates",
    "  present_url — the immersive prototype viewer for kind=canvas",
    "  share_url   — the public link, only present once visibility is 'public'",
    "  embed       — a static public preview image + ready GitHub/Markdown link for the canvas",
    "  artifacts[].github_markdown — the same card pattern for each requested/rendered artifact",
    "Hand the user share_url when they ask for something to share. Never construct URLs yourself.",
    "Embed cards are images, not iframe viewers: clicking one opens the existing public share view",
    "or the public artifact. Make private / Replace link revokes the matching card URLs too.",
    "",
    "RESULTS. Tools return structured content. Check `status`: 'ok' means everything worked,",
    "'partial' means the content was saved but something else (usually a render) did not — read",
    "`warnings` to find out what. Warnings also report unresolved asset references, so an image",
    "that silently 404s in the render is reported rather than shipped broken.",
    "code:'node_overlap' is a geometry diagnostic: two nodes on the same Page intersect. It never",
    "blocks a write and never makes status 'partial' — stacking is sometimes deliberate — but the",
    "author cannot see the result, so each pair comes back with warning.data.node_ids, both rects,",
    "overlap_area and overlap_fraction. Fix it with a canvas_doc_patch nodes.update on either rect.",
    "VERIFY. After an edit, call canvas_snapshot with a node/ref_id or narrow region first. Targeted",
    "snapshots load only intersecting iframe runtimes and return structured readiness/unresolved",
    "diagnostics. Use refresh=true to bypass a successful cached capture while debugging.",
    "Transient readiness is retried once. If an overview is downscaled, diagnostics returns",
    "suggested_regions that can be fed back as exact region snapshots for readable QA.",
    "Snapshots above the inline transport limit return inline=false and a short-lived download_url;",
    "use that URL or retry one of the suggested smaller regions instead of expecting image content.",
    "PAGINATION. canvas_find returns next_cursor; canvas_get returns an independent cursor for",
    "each included files/artifacts/versions/renders facet. On continuation, copy the first page's",
    "canvas.version into pagination.expected_version so pages cannot mix concurrent versions.",
    "Continue until is_done=true. Individual file/artifact deletion is permanent and therefore",
    "requires path plus purge:true; workspace/canvas deletion archives by default.",
    "",
    `TEMPLATES. Available as resources at canvas://templates/{id}. Ids: ${templateIds.join(", ")}.`,
    "Read one before authoring if you want a known-good starting structure.",
  ].join("\n");
}
