import type { CharacterProp, CharacterSceneProps } from "./character.js";
import { CharacterProp as CharacterPropSchema } from "./character.js";
import { phoneCharacterProp } from "./character-packs.js";

type Environment = CharacterSceneProps["environment"];
const clone = <T>(value: T): T => structuredClone(value);

export const characterBackgroundCatalog = {
  "sunrise-studio": {
    background: "#fff1d6",
    horizonY: 0.64,
    ground: "#f5c98b",
    accent: "#ff7a1a",
    layers: [
      {
        id: "sun",
        plane: "background",
        shape: "orb",
        x: 0.78,
        y: 0.2,
        width: 0.28,
        height: 0.28,
        color: "#ffd166",
        opacity: 0.8,
        parallax: 0.08,
      },
      {
        id: "desk",
        plane: "midground",
        shape: "panel",
        x: 0.5,
        y: 0.7,
        width: 0.82,
        height: 0.16,
        color: "#9a5b31",
        opacity: 1,
        parallax: 0.7,
      },
    ],
  },
  "midnight-tech": {
    background: "#07152d",
    horizonY: 0.7,
    ground: "#0d2341",
    accent: "#36d1dc",
    layers: [
      {
        id: "halo",
        plane: "background",
        shape: "orb",
        x: 0.22,
        y: 0.25,
        width: 0.46,
        height: 0.46,
        color: "#134e8e",
        opacity: 0.7,
        parallax: 0.12,
      },
      {
        id: "screen",
        plane: "midground",
        shape: "panel",
        x: 0.72,
        y: 0.38,
        width: 0.36,
        height: 0.24,
        color: "#163b63",
        opacity: 0.9,
        parallax: 0.55,
      },
    ],
  },
  "retail-pop": {
    background: "#fff7fb",
    horizonY: 0.68,
    ground: "#f8d5e5",
    accent: "#ec4899",
    layers: [
      {
        id: "arch",
        plane: "background",
        shape: "orb",
        x: 0.5,
        y: 0.42,
        width: 0.72,
        height: 0.74,
        color: "#fce7f3",
        opacity: 1,
        parallax: 0.1,
      },
      {
        id: "shelf",
        plane: "midground",
        shape: "panel",
        x: 0.5,
        y: 0.72,
        width: 0.9,
        height: 0.12,
        color: "#be185d",
        opacity: 0.8,
        parallax: 0.65,
      },
    ],
  },
  "fresh-market": {
    background: "#ecfdf5",
    horizonY: 0.66,
    ground: "#bbf7d0",
    accent: "#16a34a",
    layers: [
      {
        id: "leaf",
        plane: "background",
        shape: "sweep",
        x: 0.18,
        y: 0.3,
        width: 0.36,
        height: 0.52,
        color: "#86efac",
        opacity: 0.8,
        parallax: 0.16,
      },
      {
        id: "counter",
        plane: "midground",
        shape: "panel",
        x: 0.52,
        y: 0.74,
        width: 0.86,
        height: 0.15,
        color: "#a16207",
        opacity: 0.9,
        parallax: 0.72,
      },
    ],
  },
  "paper-editorial": {
    background: "#f8f5ec",
    horizonY: 0.76,
    ground: "#e7dfcf",
    accent: "#dc2626",
    layers: [
      {
        id: "red-disc",
        plane: "background",
        shape: "orb",
        x: 0.8,
        y: 0.18,
        width: 0.2,
        height: 0.2,
        color: "#ef4444",
        opacity: 0.9,
        parallax: 0,
      },
      {
        id: "ink-panel",
        plane: "midground",
        shape: "panel",
        x: 0.18,
        y: 0.42,
        width: 0.18,
        height: 0.5,
        color: "#292524",
        opacity: 0.92,
        parallax: 0.42,
      },
    ],
  },
  "celebration-night": {
    background: "#240046",
    horizonY: 0.72,
    ground: "#3c096c",
    accent: "#ffca3a",
    layers: [
      {
        id: "spotlight",
        plane: "background",
        shape: "sweep",
        x: 0.5,
        y: 0.38,
        width: 0.72,
        height: 0.74,
        color: "#7b2cbf",
        opacity: 0.72,
        parallax: 0.12,
      },
      {
        id: "stage",
        plane: "midground",
        shape: "panel",
        x: 0.5,
        y: 0.76,
        width: 0.86,
        height: 0.13,
        color: "#10002b",
        opacity: 1,
        parallax: 0.8,
      },
    ],
  },
} as const satisfies Record<string, Environment>;

const prop = (value: unknown): CharacterProp => CharacterPropSchema.parse(value);
const base = { x: 0.5, y: 0.55, initiallyVisible: true, scale: 1, rotation: 0 } as const;
export const characterPropCatalog: Record<string, CharacterProp> = {
  phone: phoneCharacterProp,
  laptop: prop({
    ...base,
    label: "Laptop",
    width: 150,
    height: 92,
    grip: { x: 75, y: 86 },
    shapes: [
      { kind: "rect", x: 0, y: 0, width: 150, height: 82, radius: 8, fill: "#334155" },
      { kind: "rect", x: 10, y: 9, width: 130, height: 62, radius: 3, fill: "#93c5fd" },
      { kind: "path", d: "M-12 82 L162 82 L145 98 L5 98 Z", fill: "#64748b" },
    ],
  }),
  parcel: prop({
    ...base,
    label: "Parcel",
    width: 110,
    height: 100,
    grip: { x: 55, y: 55 },
    shapes: [
      {
        kind: "rect",
        x: 0,
        y: 0,
        width: 110,
        height: 100,
        radius: 8,
        fill: "#c08457",
        stroke: "#7c4a2d",
        strokeWidth: 5,
      },
      { kind: "rect", x: 48, y: 0, width: 14, height: 100, radius: 0, fill: "#f5deb3" },
    ],
  }),
  card: prop({
    ...base,
    label: "Bank card",
    width: 120,
    height: 76,
    grip: { x: 60, y: 60 },
    shapes: [
      { kind: "rect", x: 0, y: 0, width: 120, height: 76, radius: 12, fill: "#2563eb" },
      { kind: "rect", x: 12, y: 18, width: 24, height: 18, radius: 4, fill: "#fbbf24" },
      { kind: "rect", x: 12, y: 54, width: 60, height: 6, radius: 3, fill: "#dbeafe" },
    ],
  }),
  cup: prop({
    ...base,
    label: "Coffee cup",
    width: 82,
    height: 106,
    grip: { x: 41, y: 70 },
    shapes: [
      {
        kind: "rect",
        x: 0,
        y: 8,
        width: 68,
        height: 90,
        radius: 12,
        fill: "#fef3c7",
        stroke: "#78350f",
        strokeWidth: 5,
      },
      {
        kind: "ellipse",
        x: 68,
        y: 50,
        rx: 18,
        ry: 24,
        fill: "#00000000",
        stroke: "#78350f",
        strokeWidth: 7,
      },
      { kind: "rect", x: 0, y: 0, width: 68, height: 16, radius: 6, fill: "#78350f" },
    ],
  }),
  megaphone: prop({
    ...base,
    label: "Megaphone",
    width: 142,
    height: 94,
    grip: { x: 42, y: 68 },
    shapes: [
      {
        kind: "path",
        d: "M18 28 L118 0 L118 76 L18 50 Z",
        fill: "#ef4444",
        stroke: "#7f1d1d",
        strokeWidth: 6,
      },
      { kind: "rect", x: 20, y: 48, width: 28, height: 46, radius: 7, fill: "#334155" },
      { kind: "ellipse", x: 122, y: 38, rx: 20, ry: 42, fill: "#fecaca" },
    ],
  }),
  gift: prop({
    ...base,
    label: "Gift",
    width: 112,
    height: 108,
    grip: { x: 56, y: 58 },
    shapes: [
      { kind: "rect", x: 0, y: 22, width: 112, height: 86, radius: 8, fill: "#db2777" },
      { kind: "rect", x: 47, y: 22, width: 18, height: 86, radius: 0, fill: "#fde047" },
      { kind: "path", d: "M56 24 C18 14 26 -8 54 18 C84 -10 98 16 56 24 Z", fill: "#fde047" },
    ],
  }),
  trophy: prop({
    ...base,
    label: "Trophy",
    width: 104,
    height: 130,
    grip: { x: 52, y: 90 },
    shapes: [
      {
        kind: "path",
        d: "M22 5 L82 5 Q80 70 52 82 Q24 70 22 5 Z",
        fill: "#fbbf24",
        stroke: "#92400e",
        strokeWidth: 5,
      },
      { kind: "rect", x: 45, y: 78, width: 14, height: 30, radius: 3, fill: "#d97706" },
      { kind: "rect", x: 22, y: 108, width: 60, height: 18, radius: 7, fill: "#92400e" },
    ],
  }),
  tag: prop({
    ...base,
    label: "Price tag",
    width: 124,
    height: 74,
    grip: { x: 62, y: 54 },
    shapes: [
      { kind: "path", d: "M0 10 L92 10 L124 37 L92 64 L0 64 Z", fill: "#f97316" },
      { kind: "ellipse", x: 98, y: 37, rx: 7, ry: 7, fill: "#fff7ed" },
    ],
  }),
  bulb: prop({
    ...base,
    label: "Idea bulb",
    width: 86,
    height: 124,
    grip: { x: 43, y: 100 },
    shapes: [
      {
        kind: "ellipse",
        x: 43,
        y: 42,
        rx: 38,
        ry: 40,
        fill: "#fde047",
        stroke: "#a16207",
        strokeWidth: 5,
      },
      { kind: "rect", x: 26, y: 76, width: 34, height: 34, radius: 7, fill: "#94a3b8" },
      { kind: "rect", x: 31, y: 110, width: 24, height: 10, radius: 5, fill: "#475569" },
    ],
  }),
  basket: prop({
    ...base,
    label: "Shopping basket",
    width: 142,
    height: 104,
    grip: { x: 71, y: 74 },
    shapes: [
      {
        kind: "path",
        d: "M8 34 L134 34 L118 100 L24 100 Z",
        fill: "#22c55e",
        stroke: "#14532d",
        strokeWidth: 6,
      },
      {
        kind: "path",
        d: "M34 38 Q38 -4 71 4 Q104 -4 108 38",
        fill: "#00000000",
        stroke: "#14532d",
        strokeWidth: 7,
      },
    ],
  }),
  document: prop({
    ...base,
    label: "Document",
    width: 96,
    height: 128,
    grip: { x: 48, y: 96 },
    shapes: [
      {
        kind: "rect",
        x: 0,
        y: 0,
        width: 96,
        height: 128,
        radius: 6,
        fill: "#ffffff",
        stroke: "#64748b",
        strokeWidth: 4,
      },
      { kind: "rect", x: 14, y: 26, width: 68, height: 6, radius: 3, fill: "#60a5fa" },
      { kind: "rect", x: 14, y: 45, width: 54, height: 5, radius: 2, fill: "#cbd5e1" },
      { kind: "rect", x: 14, y: 62, width: 64, height: 5, radius: 2, fill: "#cbd5e1" },
    ],
  }),
  coin: prop({
    ...base,
    label: "Savings coin",
    width: 94,
    height: 94,
    grip: { x: 47, y: 66 },
    shapes: [
      {
        kind: "ellipse",
        x: 47,
        y: 47,
        rx: 44,
        ry: 44,
        fill: "#fbbf24",
        stroke: "#92400e",
        strokeWidth: 6,
      },
      {
        kind: "path",
        d: "M47 18 L55 38 L77 39 L60 53 L65 75 L47 63 L29 75 L34 53 L17 39 L39 38 Z",
        fill: "#fff7b2",
      },
    ],
  }),
};

export type CharacterBackgroundPresetId = keyof typeof characterBackgroundCatalog;
export function createCharacterBackground(id: CharacterBackgroundPresetId): Environment {
  return clone(characterBackgroundCatalog[id]);
}
export function createCharacterProp(id: keyof typeof characterPropCatalog): CharacterProp {
  return clone(characterPropCatalog[id]!);
}
